
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.14.0
 * Query Engine version: 717184b7b35ea05dfa71a3236b7af656013e1e49
 */
Prisma.prismaVersion = {
  client: "6.14.0",
  engine: "717184b7b35ea05dfa71a3236b7af656013e1e49"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.BranchesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status',
  director_id: 'director_id',
  region: 'region',
  address: 'address',
  bank_name: 'bank_name',
  bank_account: 'bank_account',
  inn: 'inn',
  mfo: 'mfo',
  added_at: 'added_at',
  added_by: 'added_by'
};

exports.Prisma.DepartmentsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status',
  branch_id: 'branch_id',
  added_at: 'added_at'
};

exports.Prisma.Employment_ordersScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  type: 'type',
  date: 'date',
  branch_id: 'branch_id',
  department_id: 'department_id',
  position_id: 'position_id',
  order_number: 'order_number',
  note: 'note',
  added_at: 'added_at'
};

exports.Prisma.EmployeesScalarFieldEnum = {
  id: 'id',
  employee_number: 'employee_number',
  last_name: 'last_name',
  first_name: 'first_name',
  middle_name: 'middle_name',
  date_of_birth: 'date_of_birth',
  gender: 'gender',
  passport: 'passport',
  passport_expiry_date: 'passport_expiry_date',
  pinfl: 'pinfl',
  education: 'education',
  phone: 'phone',
  email: 'email',
  address: 'address',
  status: 'status',
  photo: 'photo',
  branch_id: 'branch_id',
  department_id: 'department_id',
  position_id: 'position_id',
  work_schedule_id: 'work_schedule_id',
  education_specialty: 'education_specialty',
  added_at: 'added_at',
  updated_at: 'updated_at'
};

exports.Prisma.Face_passesScalarFieldEnum = {
  id: 'id',
  date: 'date',
  identifier: 'identifier',
  photo: 'photo',
  employee_id: 'employee_id',
  door_id: 'door_id',
  face_devices_id: 'face_devices_id',
  direction: 'direction',
  source: 'source',
  latitude: 'latitude',
  longitude: 'longitude',
  added_at: 'added_at'
};

exports.Prisma.HolidaysScalarFieldEnum = {
  id: 'id',
  name: 'name',
  date_from: 'date_from',
  date_to: 'date_to',
  added_by: 'added_by',
  added_at: 'added_at'
};

exports.Prisma.PositionsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status',
  added_at: 'added_at'
};

exports.Prisma.SessionsScalarFieldEnum = {
  id: 'id',
  refresh_token: 'refresh_token',
  ip_address: 'ip_address',
  user_agent: 'user_agent',
  added_at: 'added_at',
  expires_at: 'expires_at',
  user_id: 'user_id'
};

exports.Prisma.Telegram_botsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  chat_id: 'chat_id',
  selectedEmployeeIds: 'selectedEmployeeIds',
  receive_late_report: 'receive_late_report',
  receive_event_alerts: 'receive_event_alerts',
  receive_attendance_report: 'receive_attendance_report',
  status: 'status',
  added_at: 'added_at'
};

exports.Prisma.Time_offScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  reason: 'reason',
  date_from: 'date_from',
  date_to: 'date_to',
  added_by: 'added_by',
  added_at: 'added_at',
  is_company_paid: 'is_company_paid',
  type: 'type',
  credited_hours: 'credited_hours'
};

exports.Prisma.TimesheetScalarFieldEnum = {
  id: 'id',
  month: 'month',
  year: 'year',
  day: 'day',
  worked_hours: 'worked_hours',
  intervals: 'intervals',
  user_id: 'user_id'
};

exports.Prisma.UsersScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  telegram_id: 'telegram_id',
  employee_id: 'employee_id',
  status: 'status',
  access_level: 'access_level',
  branch_access: 'branch_access',
  department_access: 'department_access',
  language: 'language',
  theme: 'theme',
  sidebar: 'sidebar',
  view_mode: 'view_mode',
  personal_menus: 'personal_menus',
  active_branch_id: 'active_branch_id',
  ignore_gps_check: 'ignore_gps_check',
  settings: 'settings',
  added_at: 'added_at'
};

exports.Prisma.MenusScalarFieldEnum = {
  id: 'id',
  name: 'name',
  path: 'path',
  parent_id: 'parent_id',
  sort_order: 'sort_order',
  module: 'module'
};

exports.Prisma.User_menu_accessScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  menu_id: 'menu_id',
  can_view: 'can_view',
  can_add: 'can_add',
  can_update: 'can_update',
  can_delete: 'can_delete'
};

exports.Prisma.Work_schedulesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  weekly_days: 'weekly_days',
  weekly_hours: 'weekly_hours',
  work_days: 'work_days',
  shifts: 'shifts',
  added_at: 'added_at',
  status: 'status',
  late_tolerance_minutes: 'late_tolerance_minutes',
  early_leave_tolerance_minutes: 'early_leave_tolerance_minutes',
  late_leave_tolerance_minutes: 'late_leave_tolerance_minutes',
  time_calc_method: 'time_calc_method'
};

exports.Prisma.Employee_schedule_historyScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  work_schedule_id: 'work_schedule_id',
  date_from: 'date_from',
  date_to: 'date_to',
  added_at: 'added_at',
  added_by: 'added_by'
};

exports.Prisma.Employee_salary_historyScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  salary_type: 'salary_type',
  amount: 'amount',
  date_from: 'date_from',
  date_to: 'date_to',
  note: 'note',
  added_at: 'added_at',
  added_by: 'added_by'
};

exports.Prisma.DoorsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status',
  branch_id: 'branch_id',
  latitude: 'latitude',
  longitude: 'longitude',
  added_at: 'added_at'
};

exports.Prisma.Face_devicesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  door_id: 'door_id',
  device_ip: 'device_ip',
  serial_number: 'serial_number',
  port: 'port',
  direction: 'direction',
  password: 'password',
  status: 'status',
  is_local: 'is_local',
  added_at: 'added_at',
  updated_at: 'updated_at'
};

exports.Prisma.GatesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  branch_id: 'branch_id',
  telegram_chat_ids: 'telegram_chat_ids',
  status: 'status',
  added_at: 'added_at',
  updated_at: 'updated_at'
};

exports.Prisma.Anpr_camerasScalarFieldEnum = {
  id: 'id',
  name: 'name',
  gate_id: 'gate_id',
  camera_ip: 'camera_ip',
  mac_address: 'mac_address',
  port: 'port',
  direction: 'direction',
  username: 'username',
  password: 'password',
  status: 'status',
  added_at: 'added_at',
  updated_at: 'updated_at'
};

exports.Prisma.Vehicle_passesScalarFieldEnum = {
  id: 'id',
  branch_id: 'branch_id',
  gate_id: 'gate_id',
  camera_id: 'camera_id',
  plate_number: 'plate_number',
  direction: 'direction',
  photo: 'photo',
  date: 'date',
  created_at: 'created_at'
};

exports.Prisma.Payroll_sheetsScalarFieldEnum = {
  id: 'id',
  month: 'month',
  year: 'year',
  status: 'status',
  added_by: 'added_by',
  added_at: 'added_at',
  approved_by: 'approved_by',
  approved_at: 'approved_at'
};

exports.Prisma.Payroll_sheet_itemsScalarFieldEnum = {
  id: 'id',
  sheet_id: 'sheet_id',
  employee_id: 'employee_id',
  base_salary: 'base_salary',
  salary_type: 'salary_type',
  worked_days: 'worked_days',
  total_work_days: 'total_work_days',
  worked_hours: 'worked_hours',
  total_work_hours: 'total_work_hours',
  accrued: 'accrued',
  debt_balance: 'debt_balance',
  debt_deduction: 'debt_deduction',
  debt_mode: 'debt_mode',
  debt_comment: 'debt_comment',
  manual_adjustment: 'manual_adjustment',
  adjustment_comment: 'adjustment_comment',
  late_minutes: 'late_minutes',
  overtime_minutes: 'overtime_minutes',
  apply_late: 'apply_late',
  apply_overtime: 'apply_overtime',
  late_amount: 'late_amount',
  overtime_amount: 'overtime_amount',
  advance_total: 'advance_total',
  net: 'net',
  salary_balance: 'salary_balance',
  paid_amount: 'paid_amount',
  status: 'status',
  payout_status: 'payout_status'
};

exports.Prisma.Payroll_payment_logsScalarFieldEnum = {
  id: 'id',
  item_id: 'item_id',
  amount: 'amount',
  payment_date: 'payment_date',
  note: 'note',
  added_at: 'added_at'
};

exports.Prisma.Salary_advancesScalarFieldEnum = {
  id: 'id',
  employee_id: 'employee_id',
  amount: 'amount',
  advance_date: 'advance_date',
  note: 'note',
  given_by: 'given_by',
  added_at: 'added_at'
};

exports.Prisma.Product_categoriesScalarFieldEnum = {
  id: 'id',
  parent_id: 'parent_id',
  name: 'name',
  status: 'status'
};

exports.Prisma.ProductsScalarFieldEnum = {
  id: 'id',
  category_id: 'category_id',
  name: 'name',
  sku: 'sku',
  barcode: 'barcode',
  description: 'description',
  min_stock: 'min_stock',
  status: 'status',
  created_at: 'created_at'
};

exports.Prisma.Stock_locationsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  usage: 'usage',
  warehouse_id: 'warehouse_id',
  is_system: 'is_system',
  note: 'note',
  status: 'status',
  created_at: 'created_at'
};

exports.Prisma.Stock_lotsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  product_id: 'product_id',
  ref: 'ref',
  expiry_date: 'expiry_date',
  note: 'note',
  created_at: 'created_at'
};

exports.Prisma.Stock_picking_typesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  sequence_prefix: 'sequence_prefix',
  src_entity_type: 'src_entity_type',
  dest_entity_type: 'dest_entity_type',
  use_create_lots: 'use_create_lots',
  use_existing_lots: 'use_existing_lots',
  status: 'status',
  created_at: 'created_at'
};

exports.Prisma.Stock_pickingsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type_id: 'type_id',
  partner_id: 'partner_id',
  src_partner_id: 'src_partner_id',
  dest_partner_id: 'dest_partner_id',
  src_warehouse_id: 'src_warehouse_id',
  dest_warehouse_id: 'dest_warehouse_id',
  origin: 'origin',
  state: 'state',
  scheduled_date: 'scheduled_date',
  date_done: 'date_done',
  note: 'note',
  added_by: 'added_by',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Stock_movesScalarFieldEnum = {
  id: 'id',
  picking_id: 'picking_id',
  product_id: 'product_id',
  lot_id: 'lot_id',
  unit_id: 'unit_id',
  qty_demand: 'qty_demand',
  qty_done: 'qty_done',
  location_src_id: 'location_src_id',
  location_dest_id: 'location_dest_id',
  state: 'state',
  price_unit: 'price_unit',
  reference: 'reference',
  date: 'date',
  note: 'note',
  added_by: 'added_by',
  created_at: 'created_at',
  manufacturing_order_id: 'manufacturing_order_id'
};

exports.Prisma.Stock_quantsScalarFieldEnum = {
  id: 'id',
  product_id: 'product_id',
  location_id: 'location_id',
  lot_id: 'lot_id',
  unit_id: 'unit_id',
  qty: 'qty',
  reserved_qty: 'reserved_qty',
  price_unit: 'price_unit',
  updated_at: 'updated_at'
};

exports.Prisma.Bill_of_materialsScalarFieldEnum = {
  id: 'id',
  product_id: 'product_id',
  unit_id: 'unit_id',
  qty: 'qty',
  type: 'type',
  note: 'note',
  status: 'status',
  created_at: 'created_at'
};

exports.Prisma.Bom_linesScalarFieldEnum = {
  id: 'id',
  bom_id: 'bom_id',
  product_id: 'product_id',
  unit_id: 'unit_id',
  qty: 'qty'
};

exports.Prisma.Manufacturing_ordersScalarFieldEnum = {
  id: 'id',
  name: 'name',
  product_id: 'product_id',
  bom_id: 'bom_id',
  lot_id: 'lot_id',
  unit_id: 'unit_id',
  qty_planned: 'qty_planned',
  qty_produced: 'qty_produced',
  location_src_id: 'location_src_id',
  location_dest_id: 'location_dest_id',
  state: 'state',
  scheduled_date: 'scheduled_date',
  date_start: 'date_start',
  date_finish: 'date_finish',
  origin: 'origin',
  note: 'note',
  added_by: 'added_by',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.UnitsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  short_name: 'short_name',
  status: 'status',
  created_at: 'created_at'
};

exports.Prisma.Partner_categoriesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status',
  created_at: 'created_at'
};

exports.Prisma.PartnersScalarFieldEnum = {
  id: 'id',
  category_id: 'category_id',
  type: 'type',
  name: 'name',
  code: 'code',
  tax_number: 'tax_number',
  contact_person: 'contact_person',
  phone: 'phone',
  email: 'email',
  address: 'address',
  note: 'note',
  supplier_location_id: 'supplier_location_id',
  customer_location_id: 'customer_location_id',
  status: 'status',
  created_at: 'created_at'
};

exports.Prisma.WarehousesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  branch_id: 'branch_id',
  note: 'note',
  status: 'status',
  created_at: 'created_at'
};

exports.Prisma.Staffing_positionScalarFieldEnum = {
  id: 'id',
  department_id: 'department_id',
  position_id: 'position_id',
  headcount: 'headcount',
  added_at: 'added_at'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};


exports.Prisma.ModelName = {
  branches: 'branches',
  departments: 'departments',
  employment_orders: 'employment_orders',
  employees: 'employees',
  face_passes: 'face_passes',
  holidays: 'holidays',
  positions: 'positions',
  sessions: 'sessions',
  telegram_bots: 'telegram_bots',
  time_off: 'time_off',
  timesheet: 'timesheet',
  users: 'users',
  menus: 'menus',
  user_menu_access: 'user_menu_access',
  work_schedules: 'work_schedules',
  employee_schedule_history: 'employee_schedule_history',
  employee_salary_history: 'employee_salary_history',
  doors: 'doors',
  face_devices: 'face_devices',
  gates: 'gates',
  anpr_cameras: 'anpr_cameras',
  vehicle_passes: 'vehicle_passes',
  payroll_sheets: 'payroll_sheets',
  payroll_sheet_items: 'payroll_sheet_items',
  payroll_payment_logs: 'payroll_payment_logs',
  salary_advances: 'salary_advances',
  product_categories: 'product_categories',
  products: 'products',
  stock_locations: 'stock_locations',
  stock_lots: 'stock_lots',
  stock_picking_types: 'stock_picking_types',
  stock_pickings: 'stock_pickings',
  stock_moves: 'stock_moves',
  stock_quants: 'stock_quants',
  bill_of_materials: 'bill_of_materials',
  bom_lines: 'bom_lines',
  manufacturing_orders: 'manufacturing_orders',
  units: 'units',
  partner_categories: 'partner_categories',
  partners: 'partners',
  warehouses: 'warehouses',
  staffing_position: 'staffing_position'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
